name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: ğŸ¼ Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ğŸ”” Grant execute permission for gradlew
        run: |
          echo ğŸ› å¦‚æœé‡åˆ°Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
          echo ğŸ’Š é‚£ä¹ˆè¯´æ˜æ˜¯å› ä¸ºgradleç›®å½•æ²¡åŒæ­¥åˆ°githubå¯¼è‡´çš„,æ£€æŸ¥ä¸‹æ˜¯å¦æ­¤ç›®å½•ä¸‹æœ‰æ–‡ä»¶æ²¡ä¸Šä¼ 
          chmod +x ./gradlew
      - name: ğŸ’ª build apk
        run: ./gradlew assembleDebug

      - run: echo "ğŸ’¡  build succeed."

      - name: ğŸ“¸ Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: demo-apk
          path: app/build/outputs/apk/debug/app-debug.apk
