# This is a basic workflow to help you get started with Actions

name: publish plugin

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  release:
    types: [ published ]
  push:
    tags:
      - 'v*'  # ä»…åœ¨æ ‡ç­¾åŒ¹é… 'v*' æ¨¡å¼æ—¶è§¦å‘

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: ðŸ¼ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Runs a single command using the runners shell
      - name: ðŸ”¥ publishing plugin
        run: |
          echo ðŸ› å¦‚æžœé‡åˆ°Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
          echo ðŸ’Š é‚£ä¹ˆè¯´æ˜Žæ˜¯å› ä¸ºgradleç›®å½•æ²¡åŒæ­¥åˆ°githubå¯¼è‡´çš„,æ£€æŸ¥ä¸‹æ˜¯å¦æ­¤ç›®å½•ä¸‹æœ‰æ–‡ä»¶æ²¡ä¸Šä¼ 
          chmod +x gradlew
          ./gradlew publishSparkPublicationToGithubPackagesRepository
        env:
          SIGN_GPG_KEY: ${{ secrets.SIGN_GPG_KEY }}
          SIGN_GPG_PASSWORD: ${{ secrets.SIGN_GPG_PASSWORD }}
          mavenCentralUsername: ${{ secrets.MAVEN_NAME }}
          mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
          GITHUB_USER: ${{ secrets.NAME_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: ðŸ’ª build apk
        run: ./gradlew assembleDebug
      - run: echo "ðŸ’¡  build succeed."

      # https://github.com/ncipollo/release-action/blob/main/README.zh-Hans.md
      - name: ðŸ–¥ï¸ Release apk
        uses: ncipollo/release-action@v1.5.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "app/build/outputs/apk/debug/*.apk"
          allowUpdates: true
          token: ${{ secrets.dev_secret }}
      - run: echo "âœ¨ â­ ðŸŒŸ  The job finish release succeed. > ${{startsWith(github.ref, 'refs/tags/')}} ðŸš€"

#      - name: Create key=value to local.properties
#        run: |
#          echo "apiKey=${{ secrets.API_KEY }}" > local.properties
#
#      - name: Read local.properties
#        id: read_local_properties
#        run: |
#          apiKey=$(grep 'apiKey' local.properties | cut -d'=' -f2)
#          echo "API_KEY=$apiKey" >> $GITHUB_ENV
